@startuml

' Reference:
' https://plantuml.com/sequence-diagram
' https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html
'
' Author: datbt9
' Date: 13/05/2024
' Jira: http://10.254.136.35:8090/pages/resumedraft.action?draftId=65714137&draftShareId=58ce2748-b779-45e3-9a12-a3720325b42c&

skinparam shadowing false
skinparam responseMessageBelowArrow false

skinparam DefaultFontColor #222
skinparam TitleFontSize 25

skinparam NoteBorderColor #teal
skinparam NoteBackgroundColor #powderblue
skinparam NoteFontColor #444

skinparam DatabaseBorderColor #teal
skinparam DatabaseBackgroundColor #bisque

skinparam sequence {
  ParticipantBorderThickness 1
  ParticipantBorderColor #teal
  ParticipantBackgroundColor #teal
  ParticipantFontColor #white
  ParticipantFontSize 14
  ParticipantFontStyle bold

  LifeLineBorderColor #teal
  LifeLineBackgroundColor #aliceblue

  ArrowColor #teal
  ActorBorderColor #teal

  GroupBorderThickness 1
  GroupBorderColor #teal
  GroupHeaderFontColor #white
  GroupBackgroundColor #teal
  GroupFontColor #teal


  ReferenceBorderThickness 1
  ReferenceBorderColor #teal
  ReferenceBackgroundColor #aliceblue
  ReferenceHeaderBackgroundColor #white
  ReferenceFontColor #teal
}

header : datbt9
title : [DD] Luồng Nhận yêu cầu lấy thông tin khách hàng
autonumber

participant "Partner" as partner
participant "Inv SPI" as spi
participant "Inv CustomerInfo" as cust
participant "Inv Config" as config
participant "Inv Transaction" as trans
participant "Customer Service" as custservice
participant "Customer EKyc Service" as custekycservice
database "Inv Cust DB" as custdb
database "Inv Config DB" as configdb
database "Inv Trans DB" as transdb

partner++
spi++

partner -> spi: Gửi yêu cầu
spi --> spi: Validate dữ liệu truyền vào

alt Không thoả mãn
    spi-->partner: Trả về lỗi
end

spi->cust:  Gửi yêu cầu lấy thông tin khách hàng
cust++
cust->config: Lấy thông tin cờ dịch vụ
config++
config->configdb: Lấy cấu hình cờ dịch vụ
configdb++
configdb-->config
configdb--
config-->cust:
config--
cust-->cust: Kiểm tra cờ dịch vụ
alt Cờ dịch vụ off:
    cust-->spi:
    spi-->partner: Trả về lỗi
end

cust->custdb: Lấy thông tin chia sẻ hồ sơ khách hàng
custdb++
custdb-->cust:
custdb--
cust-->cust: Kiểm tra trạng thái chia sẻ hồ sơ
alt Chưa chia sẻ hồ sơ
    cust-->spi:
    spi-->partner: Tra ve loi
end
cust->custdb: Lấy thông tin tài khoản khách hàng đã được đồng bộ từ đối tác
custdb++
custdb-->cust:
custdb--
cust-->cust: Kiểm tra tài khoản khách hàng
alt Không tồn tại  hoặc \n tồn tại nhưng trạng thai khác 0
    cust->custservice: Lấy thông tin khách hàng
    custservice++
    custservice-->cust
    custservice--
    cust-->cust: Kiểm tra điều kiện tài khoản
    alt Tai khoan có nguồn tiền VTP không hoạt động
        cust-->spi
        spi-->partner: Trả về lỗi
    end
end

cust->custekycservice: Lấy thông tin ekyc
custekycservice++
custekycservice-->cust:
custekycservice--
cust-->cust: Kiểm tra thông tin ekyc
alt Không đủ 3 ảnh hoặc\n loại giấy tờ không hợp lệ
    cust-->spi:
    spi-->partner: Trả về lỗi
end
cust->custdb: Cập nhật thông tin ekyc
custdb++
custdb-->cust:
custdb--
cust->trans: Thêm bản ghi về trạng thái lấy thông tin KH
trans++
trans->transdb: Thêm vào db
transdb++
transdb-->trans
transdb--
trans-->cust
trans--
cust-->spi:
spi-->partner: Trả về thành công

cust--

spi--
partner--
@enduml